"""Cross-language conformance suite (P9).

Runs the *identical* fixture files as
``packages/layout-core/src/__tests__/conformance.test.ts``. The ``expected``
blocks were generated by the TypeScript compiler, so the ``docHash`` comparison
here is the load-bearing assertion: it proves the two implementations produce
byte-identical canonical output, and therefore that Publish will not reject
itself with ``COMPILER_DRIFT``.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from app.layout import (
    RULE_CODES,
    CapacityTarget,
    FitItem,
    LayoutGraph,
    build_layout,
    codes_of,
    item_fits,
    summarize_diagnostic,
    validate_document,
)

FIXTURES_DIR = Path(__file__).resolve().parents[3] / "fixtures" / "layout-conformance"
PLACEMENT_FILE = (
    Path(__file__).resolve().parents[3] / "fixtures" / "placement-conformance" / "cases.json"
)
FIXTURE_FILES = sorted(FIXTURES_DIR.glob("*.json"))

PARAMS = [pytest.param(path, id=path.name) for path in FIXTURE_FILES]


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def summarize(graph: LayoutGraph) -> dict:
    """Must match `summarise()` in the TypeScript conformance test exactly.

    The full diagnostic list — not just a set of codes — is compared, so ordering,
    severity, entityRefs and computed ``data`` are all pinned across runtimes.
    """
    return {
        "publishable": graph.publishable,
        "binCount": len(graph.bins),
        "bayCount": len(graph.bays),
        "diagnosticCodes": codes_of(graph.diagnostics),
        "diagnostics": [summarize_diagnostic(d) for d in graph.diagnostics],
        "docHash": graph.hash,
        "firstBinCode": graph.bins[0].code if graph.bins else None,
        "lastBinCode": graph.bins[-1].code if graph.bins else None,
    }


def test_fixture_set_is_present() -> None:
    assert len(FIXTURE_FILES) >= 19, f"expected at least 19 fixtures in {FIXTURES_DIR}"


@pytest.mark.parametrize("path", PARAMS)
def test_matches_typescript_expectations(path: Path) -> None:
    fixture = load(path)

    assert fixture["expected"], (
        f"{path.name} has an empty 'expected' block — run: npm run gen:hashes"
    )

    # The generated JSON Schema is the contract; every fixture must satisfy it.
    validate_document(fixture["doc"])

    assert summarize(build_layout(fixture["doc"])) == fixture["expected"]


@pytest.mark.parametrize("path", PARAMS)
def test_every_fixture_triggers_the_rules_it_targets(path: Path) -> None:
    fixture = load(path)
    emitted = {d.code for d in build_layout(fixture["doc"]).diagnostics}

    for target in fixture.get("targets", []):
        assert target in emitted, f"{path.name} declares target '{target}' but does not emit it"


def test_every_registered_rule_is_covered() -> None:
    covered: set[str] = set()

    for path in FIXTURE_FILES:
        for diagnostic in build_layout(load(path)["doc"]).diagnostics:
            covered.add(diagnostic.code)

    for case in load(PLACEMENT_FILE)["cases"]:
        result = item_fits(to_bin(case), to_item(case), case["qty"])
        if result.failure is not None:
            covered.add(result.failure.code)

    uncovered = [code for code in RULE_CODES if code not in covered]
    assert not uncovered, f"rules with no test coverage: {', '.join(uncovered)}"


def test_no_fixture_emits_a_code_outside_the_registry() -> None:
    known = set(RULE_CODES)

    for path in FIXTURE_FILES:
        for diagnostic in build_layout(load(path)["doc"]).diagnostics:
            assert diagnostic.code in known, f"{path.name} emitted unknown code {diagnostic.code}"


@pytest.mark.parametrize("path", PARAMS)
def test_hash_is_stable_across_repeated_runs(path: Path) -> None:
    fixture = load(path)
    first = build_layout(fixture["doc"])
    second = build_layout(fixture["doc"])

    assert first.hash == second.hash
    assert first.bins == second.bins


@pytest.mark.parametrize("path", PARAMS)
def test_bin_codes_are_unique_unless_the_fixture_tests_duplicates(path: Path) -> None:
    fixture = load(path)
    graph = build_layout(fixture["doc"])

    if any(d.code == "BIN_CODE_DUPLICATE" for d in graph.diagnostics):
        pytest.skip("fixture deliberately produces duplicate codes")

    codes = [bin_.code for bin_ in graph.bins]
    assert len(codes) == len(set(codes)), f"{path.name} produced duplicate bin codes"


def to_bin(case: dict) -> CapacityTarget:
    return CapacityTarget(
        width_m=case["bin"]["widthM"],
        height_m=case["bin"]["heightM"],
        depth_m=case["bin"]["depthM"],
        capacity_m3=case["bin"]["capacityM3"],
        max_weight_kg=case["bin"]["maxWeightKg"],
    )


def to_item(case: dict) -> FitItem:
    return FitItem(
        width_m=case["item"]["widthM"],
        height_m=case["item"]["heightM"],
        depth_m=case["item"]["depthM"],
        weight_kg=case["item"]["weightKg"],
        rotatable=case["item"]["rotatable"],
    )


PLACEMENT_CASES = load(PLACEMENT_FILE)["cases"]


@pytest.mark.parametrize("case", PLACEMENT_CASES, ids=lambda c: c["name"])
def test_placement_case_matches_typescript_expectations(case: dict) -> None:
    assert case["expected"], (
        f"{case['name']} has an empty 'expected' block — run: npm run gen:hashes"
    )

    result = item_fits(to_bin(case), to_item(case), case["qty"])

    assert {
        "fits": result.fits,
        "code": result.failure.code if result.failure else None,
        "orientation": list(result.orientation) if result.orientation else None,
    } == case["expected"]
