/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Db */
        get: operations["health_db_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/layout/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Layout
         * @description Run the rules without writing anything. Used by the editor's diagnostics panel.
         */
        post: operations["validate_layout_api_layout_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/layout/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compile Layout
         * @description Compile and return the derived bins, checking the client hash if supplied.
         */
        post: operations["compile_layout_api_layout_compile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Warehouses */
        get: operations["list_warehouses_api_warehouses_get"];
        put?: never;
        /**
         * Create Warehouse
         * @description Create a warehouse, optionally seeding it with a document.
         *
         *     When ``doc`` is supplied it wins outright — including its own footprint — because
         *     the document is the source of truth and a payload whose footprint disagreed with
         *     its document would otherwise create two conflicting records.
         */
        post: operations["create_warehouse_api_warehouses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouses/{warehouse_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Warehouse Detail */
        get: operations["get_warehouse_detail_api_warehouses__warehouse_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouses/{warehouse_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Draft
         * @description Autosave. Debounced by the client; guarded by the revision token here.
         */
        put: operations["put_draft_api_warehouses__warehouse_id__draft_put"];
        post?: never;
        /**
         * Discard Draft
         * @description Throw the draft away, keeping any published version intact.
         *
         *     A discard bumps the revision too: a client that still holds the old token must
         *     find out that its working copy is no longer the server's.
         */
        delete: operations["discard_draft_api_warehouses__warehouse_id__draft_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouses/{warehouse_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Warehouse Layout
         * @description Compile without writing. The editor's pre-flight for a save or a publish.
         */
        post: operations["validate_warehouse_layout_api_warehouses__warehouse_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouses/{warehouse_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Warehouse Layout
         * @description Validate, materialise and publish in one transaction.
         *
         *     Idempotent on ``doc_hash``: publishing the document that is already live returns
         *     the existing version with ``changed: false``.
         */
        post: operations["publish_warehouse_layout_api_warehouses__warehouse_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouses/{warehouse_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["list_versions_api_warehouses__warehouse_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouses/{warehouse_id}/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Published Layout
         * @description The published layout for Operate mode.
         *
         *     Bins are read from the materialised rows rather than recompiled, because those
         *     rows carry the surrogate ids that placements reference. The document is also
         *     recompiled and its hash returned alongside, so a snapshot that no longer matches
         *     what the compiler would produce today is visible as ``conflicts`` instead of
         *     being silently served.
         */
        get: operations["get_published_layout_api_warehouses__warehouse_id__layout_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouses/{warehouse_id}/skus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Skus */
        get: operations["list_skus_api_warehouses__warehouse_id__skus_get"];
        put?: never;
        /** Create Sku */
        post: operations["create_sku_api_warehouses__warehouse_id__skus_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skus/{sku_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Sku
         * @description Edit a SKU in place.
         *
         *     This does **not** re-validate existing placements. Shrinking a SKU cannot invalidate
         *     anything, but growing one can, and silently deleting inventory because a dimension
         *     changed would be worse than leaving a placement that a later check flags. The
         *     placement list reports each bin's utilisation, so an over-capacity bin is visible.
         */
        put: operations["update_sku_api_skus__sku_id__put"];
        post?: never;
        /** Delete Sku */
        delete: operations["delete_sku_api_skus__sku_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouses/{warehouse_id}/placements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Warehouse Placements */
        get: operations["list_warehouse_placements_api_warehouses__warehouse_id__placements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouses/{warehouse_id}/utilization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Utilization */
        get: operations["get_utilization_api_warehouses__warehouse_id__utilization_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bins/{bin_id}/placements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bin Placements */
        get: operations["get_bin_placements_api_bins__bin_id__placements_get"];
        put?: never;
        /**
         * Create Placement
         * @description Place a SKU in a bin, revalidating on the server.
         *
         *     The client checks the same thing before the drop, so a 200 here means both sides
         *     agreed and a 422 means the codes should match what the client computed.
         */
        post: operations["create_placement_api_bins__bin_id__placements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/placements/{placement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Placement */
        delete: operations["delete_placement_api_placements__placement_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouses/{warehouse_id}/placements/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Create Placements
         * @description Fill many bins at once, with a verdict per bin rather than all-or-nothing.
         */
        post: operations["bulk_create_placements_api_warehouses__warehouse_id__placements_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BinPlacementsOut
         * @description A bin and everything in it, with the capacity arithmetic already done.
         *
         *     `remaining*` is computed from the *other* placements, so the client can render a
         *     drag ghost from the same numbers the server checks rather than re-deriving them.
         */
        BinPlacementsOut: {
            /**
             * Binid
             * Format: uuid
             */
            binId: string;
            /** Bincode */
            binCode: string;
            /** Capacitym3 */
            capacityM3: number;
            /** Maxweightkg */
            maxWeightKg: number | null;
            /** Usedvolumem3 */
            usedVolumeM3: number;
            /** Usedweightkg */
            usedWeightKg: number;
            /** Remainingvolumem3 */
            remainingVolumeM3: number;
            /** Remainingweightkg */
            remainingWeightKg: number | null;
            /** Utilization */
            utilization: number;
            /** Placements */
            placements: components["schemas"]["PlacementOut"][];
        };
        /** BulkPlacementIn */
        BulkPlacementIn: {
            /**
             * Skuid
             * Format: uuid
             */
            skuId: string;
            /** Qty */
            qty: number;
            /** Binids */
            binIds: string[];
        };
        /** BulkPlacementItem */
        BulkPlacementItem: {
            /**
             * Binid
             * Format: uuid
             */
            binId: string;
            /** Bincode */
            binCode?: string | null;
            /** Ok */
            ok: boolean;
            /** Code */
            code?: string | null;
            /**
             * Message
             * @default
             */
            message: string;
            placement?: components["schemas"]["PlacementOut"] | null;
        };
        /**
         * BulkPlacementOut
         * @description Every bin gets its own verdict: a bulk fill is per-bin, not all-or-nothing.
         */
        BulkPlacementOut: {
            /** Placed */
            placed: number;
            /** Rejected */
            rejected: number;
            /** Results */
            results: components["schemas"]["BulkPlacementItem"][];
        };
        /** CompileResponse */
        CompileResponse: {
            /** Dochash */
            docHash: string;
            /** Publishable */
            publishable: boolean;
            /** Bincount */
            binCount: number;
            /** Baycount */
            bayCount: number;
            /** Errorcount */
            errorCount: number;
            /** Warningcount */
            warningCount: number;
            /** Diagnostics */
            diagnostics: {
                [key: string]: unknown;
            }[];
            /** Bins */
            bins?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** DraftOut */
        DraftOut: {
            /**
             * Warehouseid
             * Format: uuid
             */
            warehouseId: string;
            /** Version */
            version: number;
            /** Draftrevision */
            draftRevision: number;
            /** Dochash */
            docHash: string;
            /** Publishable */
            publishable: boolean;
            /** Errorcount */
            errorCount: number;
            /** Warningcount */
            warningCount: number;
            /** Diagnostics */
            diagnostics: {
                [key: string]: unknown;
            }[];
            /**
             * Savedat
             * Format: date-time
             */
            savedAt: string;
        };
        /** DraftPut */
        DraftPut: {
            /** Doc */
            doc: {
                [key: string]: unknown;
            };
            /** Clientdochash */
            clientDocHash?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LayoutPayload */
        LayoutPayload: {
            /** Doc */
            doc: {
                [key: string]: unknown;
            };
            /** Clientdochash */
            clientDocHash?: string | null;
        };
        /** PlacementIn */
        PlacementIn: {
            /**
             * Skuid
             * Format: uuid
             */
            skuId: string;
            /** Qty */
            qty: number;
        };
        /** PlacementOut */
        PlacementOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Binid
             * Format: uuid
             */
            binId: string;
            /** Bincode */
            binCode: string;
            /**
             * Skuid
             * Format: uuid
             */
            skuId: string;
            /** Sku */
            sku: string;
            /** Qty */
            qty: number;
            /** Volumeusedm3 */
            volumeUsedM3: number;
            /** Weightusedkg */
            weightUsedKg: number;
        };
        /** PublishOut */
        PublishOut: {
            /**
             * Warehouseid
             * Format: uuid
             */
            warehouseId: string;
            /** Version */
            version: number;
            /** Dochash */
            docHash: string;
            /** Status */
            status: string;
            /** Changed */
            changed: boolean;
            /** Bincount */
            binCount: number;
            /** Baycount */
            bayCount: number;
            /** Errorcount */
            errorCount: number;
            /** Warningcount */
            warningCount: number;
            /** Diagnostics */
            diagnostics: {
                [key: string]: unknown;
            }[];
            /** Orphanedplacements */
            orphanedPlacements: {
                [key: string]: unknown;
            }[];
        };
        /** PublishRequest */
        PublishRequest: {
            /** Doc */
            doc: {
                [key: string]: unknown;
            };
            /** Clientdochash */
            clientDocHash?: string | null;
            /** Createdby */
            createdBy?: string | null;
        };
        /**
         * PublishedLayoutOut
         * @description What Operate mode reads.
         *
         *     Bins come from the materialised rows rather than from a fresh compile, because
         *     those rows carry the surrogate ids that placements reference. ``docHash`` and
         *     ``recompiledDocHash`` are both returned so drift between the snapshot and the
         *     current compiler is visible instead of assumed away.
         */
        PublishedLayoutOut: {
            /**
             * Warehouseid
             * Format: uuid
             */
            warehouseId: string;
            /** Code */
            code: string;
            /** Version */
            version: number;
            /** Dochash */
            docHash: string;
            /** Recompileddochash */
            recompiledDocHash: string;
            /** Publishedat */
            publishedAt: string | null;
            /** Bins */
            bins: {
                [key: string]: unknown;
            }[];
            /** Conflicts */
            conflicts?: string[];
        };
        /** SkuIn */
        SkuIn: {
            /** Sku */
            sku: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** Widthm */
            widthM: number;
            /** Heightm */
            heightM: number;
            /** Depthm */
            depthM: number;
            /** Weightkg */
            weightKg: number;
            /**
             * Stackable
             * @default true
             */
            stackable: boolean;
            /**
             * Rotatable
             * @default true
             */
            rotatable: boolean;
            /**
             * Hazmat
             * @default false
             */
            hazmat: boolean;
        };
        /** SkuOut */
        SkuOut: {
            /** Sku */
            sku: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** Widthm */
            widthM: number;
            /** Heightm */
            heightM: number;
            /** Depthm */
            depthM: number;
            /** Weightkg */
            weightKg: number;
            /**
             * Stackable
             * @default true
             */
            stackable: boolean;
            /**
             * Rotatable
             * @default true
             */
            rotatable: boolean;
            /**
             * Hazmat
             * @default false
             */
            hazmat: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Placedqty
             * @default 0
             */
            placedQty: number;
        };
        /**
         * UtilizationOut
         * @description Heatmap input: utilisation per bin, and the bins that hold nothing.
         */
        UtilizationOut: {
            /**
             * Warehouseid
             * Format: uuid
             */
            warehouseId: string;
            /** Bincount */
            binCount: number;
            /** Utilizedbins */
            utilizedBins: number;
            /** Emptybins */
            emptyBins: number;
            /** Entries */
            entries: {
                [key: string]: unknown;
            }[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionOut */
        VersionOut: {
            /** Version */
            version: number;
            /** Status */
            status: string;
            /** Dochash */
            docHash: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Publishedat */
            publishedAt?: string | null;
            /** Createdby */
            createdBy?: string | null;
            /**
             * Errorcount
             * @default 0
             */
            errorCount: number;
            /**
             * Warningcount
             * @default 0
             */
            warningCount: number;
            /** Orphanedplacements */
            orphanedPlacements?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * WarehouseCreate
         * @description A warehouse starts from a footprint, with an optional first document.
         *
         *     Supplying ``doc`` lets the client seed a new warehouse from the layout it already
         *     has open instead of round-tripping a blank one through a draft save.
         */
        WarehouseCreate: {
            /** Code */
            code: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** Lengthm */
            lengthM: number;
            /** Widthm */
            widthM: number;
            /** Heightm */
            heightM: number;
            /** Origin */
            origin?: {
                [key: string]: number;
            } | null;
            /** Doc */
            doc?: {
                [key: string]: unknown;
            } | null;
        };
        /** WarehouseOut */
        WarehouseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Lengthm */
            lengthM: number;
            /** Widthm */
            widthM: number;
            /** Heightm */
            heightM: number;
            /** Draftrevision */
            draftRevision: number;
            draft?: components["schemas"]["VersionOut"] | null;
            published?: components["schemas"]["VersionOut"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_db_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    validate_layout_api_layout_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayoutPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compile_layout_api_layout_compile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayoutPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_warehouses_api_warehouses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarehouseOut"][];
                };
            };
        };
    };
    create_warehouse_api_warehouses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WarehouseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarehouseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_warehouse_detail_api_warehouses__warehouse_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                warehouse_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarehouseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_draft_api_warehouses__warehouse_id__draft_put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                warehouse_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftPut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_draft_api_warehouses__warehouse_id__draft_delete: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                warehouse_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_warehouse_layout_api_warehouses__warehouse_id__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                warehouse_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_warehouse_layout_api_warehouses__warehouse_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                warehouse_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_warehouses__warehouse_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                warehouse_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_published_layout_api_warehouses__warehouse_id__layout_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                warehouse_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishedLayoutOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skus_api_warehouses__warehouse_id__skus_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                warehouse_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkuOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_sku_api_warehouses__warehouse_id__skus_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                warehouse_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkuIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkuOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_sku_api_skus__sku_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkuIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkuOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_sku_api_skus__sku_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_warehouse_placements_api_warehouses__warehouse_id__placements_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                warehouse_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacementOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_utilization_api_warehouses__warehouse_id__utilization_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                warehouse_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UtilizationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bin_placements_api_bins__bin_id__placements_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bin_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BinPlacementsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_placement_api_bins__bin_id__placements_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bin_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlacementIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_placement_api_placements__placement_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_create_placements_api_warehouses__warehouse_id__placements_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                warehouse_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkPlacementIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkPlacementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
