"""SQLAlchemy 2.0 declarative base.

Two conventions here are load-bearing for Alembic rather than cosmetic:

* ``NAMING_CONVENTION`` gives every constraint a deterministic name. Without it,
  autogenerated diffs are unstable and ``downgrade()`` cannot address constraints.
* ``metadata`` is reserved on ``DeclarativeBase``, so the attribute is
  ``metadata_`` while the column stays ``metadata``.
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime

from sqlalchemy import MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(server_default=func.now(), onupdate=func.now())


class VersionStatus(enum.StrEnum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    ARCHIVED = "ARCHIVED"


def new_uuid() -> uuid.UUID:
    return uuid.uuid4()
